# Travis-CI Build for gf2
# see travis-ci.org for details

language: cpp

branches:
  only:
    - master

env:
  global:
    - secure: "XWVopDnLVitSI1I8ZyasnD68/2E1JN31ZTXzY5DQf94wjgqC/MjkhDyERU8W5EHnAwCtW4ReYzjwAUSZwVBV10+US4fE6uxGJ4BboL/Vx+DBIrUKhPnln3IZoksom8UjrDK6vMfNjMWmUB79WuECfWD0cDNPy0VloD7n83TIBbsaEAlFYa420e1yx+ahat+f4PncI14BS/BeGDGitK2OReatqV96HxSYAC3htanNjeSoiPkNUmdyxXxczdp7s4PdXzsRfydHekde03BlcXlIdhO2gVUHaQkKyvlNrPUs2qsm3eB2CZFA8A/AjlNsYaCDAaPLR/tYN61Ezl0ccfkg72zNhKILY2xn4LBkTsN08CD1XrxjkXgEBskWYsI1zKeStu3lyuMVfbs+FvLVXbyYVjxsvOKOmHi7fGpyVjUcOOAxi6CFQD+mTDg1sia043OQ+5QuzGEQmqWJbC2srNpRXeOfrBn2ARSq3lkKKkpEAXpVqyx1l5gYMRXL/Wjz7AAZOtJ6FZfpGVI/qOiIsuU4JJBvGfP84uXbDTkzAp54MupIYaut+oz2+WLxhk0sfFtKNS0ZG968TudbMM9fl+xBQLgVfLPbNsgeGb/njCgtUSCGCBtZSKeEkVXUiGsHQGcqUnQVfY+Nc7OydXNh6Yj644YDdCVDLW/4ziBGQZJHpsw="

matrix:
  include:
  - os: linux
    compiler: clang
    env:
    - COVERITY_SCAN_PROJECT_NAME="$TRAVIS_REPO_SLUG"
    - COVERITY_SCAN_BRANCH_PATTERN="master"
    - COVERITY_SCAN_NOTIFICATION_EMAIL="agievich@gmail.com"
    - COVERITY_SCAN_BUILD_COMMAND_PREPEND="cmake -DCMAKE_BUILD_TYPE=Debug -DBUILD_FAST=ON"
    - COVERITY_SCAN_BUILD_COMMAND="make"
    script:
    - curl -s 'https://scan.coverity.com/scripts/travisci_build_coverity_scan.sh' | bash || true
  - os: linux
    compiler: gcc
    dist: bionic
    env: BUILD_TYPE=Memsan
  - os: osx
    compiler: clang
    env: BUILD_TYPE=Check
  - os: linux
    compiler: bionic
    sudo: required
    env: BUILD_TYPE=Coverage
    install:
    - sudo apt-get install -y lcov
    after_success:
    - lcov -c -i -d src -o coverage_base.info
    - test/testgf2
    - lcov -c -d src -o coverage_test.info
    - lcov -a coverage_base.info -a coverage_test.info -o coverage.info
    - bash <(curl -s https://codecov.io/bash) -f coverage.info

script: 
  - mkdir build && cd build 
  - cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE ..
  - make
  - ctest --verbose
