# Build and run tests on the baseline platform

name: build

on:
  push:
    branches: master
  pull_request:
    branches: master

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
        - BUILD_TYPE: Release
          CXX: g++
        - BUILD_TYPE: Check
          CXX: g++
        - BUILD_TYPE: ASan
          CXX: g++
        - BUILD_TYPE: MemSan
          CXX: clang++
        - BUILD_TYPE: Debug
          CXX: clang++
    steps:
    - name: Get source
      uses: actions/checkout@v3
    - name: Configure CMake
      run: > 
        CXX=${{matrix.CXX}} cmake 
        -B ${{github.workspace}}/build 
        -DCMAKE_BUILD_TYPE=${{matrix.BUILD_TYPE}} 
    - name: Build
      run: cmake --build ${{github.workspace}}/build
    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest --verbose
